title: Ryan Denmark
url: https://rwdenmark.github.io
author: Ryan Denmark

# Don't process these files/folders into the built site
exclude:
  - README.md
  - .gitignore
  - .github

# GitHub Pages allows these plugins out of the box
plugins:
  - jekyll-sitemap

